# Generated by Django 5.0.6 on 2024-11-26 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='BotUser',
        ),
    ]
