# Generated by Django 5.0.6 on 2024-11-27 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_rename_user_botuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='role',
            field=models.CharField(choices=[('listener', 'Слушатель'), ('speaker', 'Спикер')], max_length=10),
        ),
    ]
