# Generated by Django 5.0.6 on 2024-11-27 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_botuser_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botuser',
            options={'verbose_name': 'Пользователь бота', 'verbose_name_plural': 'Пользователи бота'},
        ),
        migrations.AddField(
            model_name='botuser',
            name='about_myself',
            field=models.TextField(blank=True, verbose_name='О себе'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Возраст'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='consent_given',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Согласие на обработку данных'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='is_active_speaker',
            field=models.BooleanField(default=False, verbose_name='Статус активного спикера'),
        ),
        migrations.AddField(
            model_name='botuser',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='role',
            field=models.CharField(choices=[('listener', 'Слушатель'), ('speaker', 'Спикер')], default='listener', max_length=10, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='telegram_id',
            field=models.BigIntegerField(unique=True, verbose_name='Telegram ID'),
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Сумма доната')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.botuser')),
            ],
            options={
                'verbose_name': 'Донат',
                'verbose_name_plural': 'Донаты',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название выступления')),
                ('description', models.TextField(blank=True, verbose_name='Описание выступления')),
                ('start_time', models.DateTimeField(verbose_name='Запланированное время - начало')),
                ('end_time', models.DateTimeField(verbose_name='Запланированное время - конец')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaking_events', to='bot.botuser')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Вопрос')),
                ('asked_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В процессе'), ('answered', 'Отвеченный')], default='new', max_length=20, verbose_name='Статус вопроса')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.botuser')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
    ]
