# Generated by Django 5.0.6 on 2024-11-28 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_alter_botuser_options_botuser_about_myself_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botuser',
            name='is_active_speaker',
        ),
        migrations.RemoveField(
            model_name='question',
            name='asked_at',
        ),
        migrations.RemoveField(
            model_name='question',
            name='status',
        ),
        migrations.AddField(
            model_name='botuser',
            name='username',
            field=models.CharField(default='Без юзернейма', max_length=255, verbose_name='Username'),
        ),
        migrations.AddField(
            model_name='event',
            name='is_active_event',
            field=models.BooleanField(default=False, verbose_name='Статус активного спикера'),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Время начала события')),
                ('end_time', models.DateTimeField(verbose_name='Время окончания события')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.botuser')),
            ],
        ),
    ]
