# Generated by Django 5.0.6 on 2024-11-29 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_remove_botuser_is_active_speaker_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'Расписание', 'verbose_name_plural': 'Расписание'},
        ),
        migrations.RemoveField(
            model_name='donation',
            name='user',
        ),
        migrations.AddField(
            model_name='donation',
            name='donor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='donations_made', to='bot.botuser', verbose_name='Кто задонатил'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donation',
            name='speaker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='donations_received', to='bot.botuser', verbose_name='Кому задонатили'),
            preserve_default=False,
        ),
    ]
