# Generated by Django 5.0.6 on 2024-12-01 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_alter_schedule_options_remove_donation_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
